name: Leandro Oriente
markdown: redcarpet
permalink: /:title
paginate: 5
port: 9001

title : Leandro Oriente
tagline: Desenvolvedor Front End
author :
  name : Leandro Oriente
  email : leandroriente@gmail.com
  github : http://github.com/leandrooriente
  facebook : http://facebook.com/leandrooriente
  googleplus : https://plus.google.com/+LeandroOriente?rel=author
  500px : http://500px.com/leandrooriente
  linkedin : http://www.linkedin.com/in/leandrooriente
  instagram : http://instagram.com/leandrooriente

markdown: kramdown
kramdown:
  use_coderay: true
  parse_block_html: true

highlighter: pygments

assets:
  js_compressor:  uglifier
  css_compressor: sass

sass:
  sass_dir: assets/stylesheet
  style: :compressed

production_url : http://leandrooriente.com
url : http://leandrooriente.com

theme :
  comments :
    provider : disqus
    disqus :
      short_name : leandrooriente

analytics :
    provider : google 
    google : 
        tracking_id : 'UA-25340215-1'
